/* version 0.1 du                                                         */
/*  dernière modification :                                               */
/*         22 02 2013 (SD)                                                */
/*  auteur :                                                              */
/*         SD Samuel Déom (sdeom@epadesa.fr)                              */

/* Pour fonctionner il faut inclure préalablement les boites à outils :   */
/*  aucune boite à outils                                                 */


proc,SchemaRf=registrefoncier
proc,TblFonds=fonds
proc,TblPrcl=fonds_parcelle
proc,TblVol=fonds_volume
proc,TblEddv=volumetrie_descriptif
