/* version 0.1 du                                                           */
/*  dernière modification :                                                 */
/*         01 06 2015 (SD)                                                  */
/*  auteur :                                                                */
/*         SD Samuel Déom (sdeom@epadesa.fr)                                */

/* Pour fonctionner il faut inclure préalablement les boites à outils :     */
/*  epRalOutils                                                             */
/*  epEdvOutils                                                             */
/*  epTexteOutils (pour epRalOutils et epEdvOutils)                         */
/*  epNumOutils   (pour epRalOutils et epEdvOutils)                         */

/* Procédures de l'environnement                                            */


/* Liste des routines                                                       */


/*--------------------------------------------------------------------------*/
/*                                ROUTINES                                  */
/*                         par ordre alphabétique                           */
/*--------------------------------------------------------------------------*/

